version: '2'
services:
    jhipapp-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        command: mongos --configdb jhipapp-mongodb-config
    jhipapp-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    jhipapp-mongodb-config:
        image: mongo:3.6.3
        container_name: jhipapp-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
